version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks: 
      - proxy-tier

  ssl-generator:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: 
      - proxy-tier

  more-than-blogs-api:
    restart: always
    image: more-than-blogs-api
    container_name: more-than-blogs-api
    build: ./more-than-blogs-api
    volumes: 
      - ./more-than-blogs-api/build:/app
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=api.morethanblog.tk
      - LETSENCRYPT_HOST=api.morethanblog.tk
    networks: 
      - proxy-tier

  more-than-blogs-landing:
    restart: always
    image: more-than-blogs-landing
    container_name: more-than-blogs-landing
    build: ./more-than-blogs-landing
    volumes:
      - ./more-than-blogs-landing/build:/usr/share/nginx/html
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=morethanblog.tk
      - LETSENCRYPT_HOST=morethanblog.tk
    networks: 
      - proxy-tier

  more-than-blogs-admin:
    restart: always
    image: more-than-blogs-admin
    container_name: more-than-blogs-admin
    build: ./more-than-blogs-admin
    volumes:
      - ./more-than-blogs-admin/build:/usr/share/nginx/html
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=admin.morethanblog.tk
      - LETSENCRYPT_HOST=admin.morethanblog.tk
    networks: 
      - proxy-tier

volumes:
  vhost:
  html:
  certs:

networks:
  proxy-tier:
    external:
      name: nginx-proxy